export const BG_MAP = {
  owari_plains_dusk:               'bg-field',
  owari_province_dawn:             'bg-dawn',
  owari_armory_night:              'bg-night',
  okehazama_battlefield:           'bg-battle',
  okehazama_aftermath:             'bg-dawn',
  kyoto_road_arrival:              'bg-court',
  kyoto_imperial_gate:             'bg-court',
  kyoto_streets_market:            'bg-court',
  shogunate_audience_hall:         'bg-court',
  honnoji_temple_night_arrival:    'bg-temple',
  honnoji_temple_courtyard_torches:'bg-battle',
  honnoji_inner_hall_smoke:        'bg-battle',
  honnoji_inner_hall_desk:         'bg-battle',
  honnoji_burning_inner_hall:      'bg-battle',
  honnoji_burning_final:           'bg-battle',
  honnoji_dawn_aftermath:          'bg-dawn',
  mino_border_autumn_fog:          'bg-field',
  mino_dosan_manor:                'bg-court',
  mino_garden_autumn:              'bg-field',
  mino_garden_autumn_late:         'bg-field',
  mino_garden_sunset:              'bg-field',
  mino_road_evening:               'bg-field',
  mino_border_pass_tense:          'bg-field',
  mino_border_pass_skirmish:       'bg-battle',
  mino_border_pass_clear:          'bg-dawn',
  mino_border_retreat:             'bg-field',
  mino_border_negotiation:         'bg-field',
  mino_yoshitatsu_army_road:       'bg-battle',
  mountain_pass_hidden:            'bg-night',
  gifu_castle_tower_night:         'bg-night',
  japan_map_painted_scroll:        'bg-map',
  nagashino_river_low:             'bg-water',
  default:                         'bg-default',
};

export const BG_CLASSES = [...new Set(Object.values(BG_MAP))];